service: apig_cognito

frameworkVersion: '>=1.26.1 <2.0.0'

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

functions:
  root:
    name: root-${opt:stage}
    handler: handler.get
    events:
      - http:
          path: /
          method: get
          cors: true
